// Production runtime config — baked into the nginx image, served at /config.js.
// In upstream ntfy this is generated by the server; we serve the UI standalone, so we
// point base_url at the ntfy API host (the server now lives at ntfy.eli.kr).
// web_push_public_key must be copied from the ntfy server config if web push is wanted.
var config = {
  base_url: "https://ntfy.eli.kr",
  app_root: "/",
  enable_login: true,
  require_login: false,
  enable_signup: true,
  enable_payments: false,
  enable_reservations: true,
  enable_emails: true,
  enable_calls: true,
  enable_web_push: false,
  billing_contact: "",
  web_push_public_key: "",
  disallowed_topics: ["docs", "static", "file", "app", "account", "settings", "signup", "login", "v1"],
  config_hash: "prod",
};
